"""empty message

Revision ID: 1c399a234797
Revises: 2d10ed5de194
Create Date: 2021-05-15 06:24:48.626590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c399a234797'
down_revision = '2d10ed5de194'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dtm', 'author_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dtm', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
