"""empty message

Revision ID: 9f8be1094455
Revises: 
Create Date: 2021-05-15 05:15:33.089508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f8be1094455'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('author_id')
    )
    op.create_table('dtm',
    sa.Column('dtm_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('languages', sa.String(), nullable=True),
    sa.Column('download_links', sa.String(), nullable=True),
    sa.Column('copyright_info', sa.String(), nullable=True),
    sa.Column('foreign_landing_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.author_id'], ),
    sa.PrimaryKeyConstraint('dtm_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dtm')
    op.drop_table('author')
    # ### end Alembic commands ###
